name: traffic_env
channels:
  - conda-forge
dependencies:
  - matplotlib >= 3.8
  - pandas >= 2.0
  - pip >= 24.0
  - python = 3.12
  - sqlite >= 3.50
  - pip:
      - plotly == 5.24.0
      - seaborn == 0.13.2
